#!/home/nox/Development/chessley-tan/chessley-venv/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'wheel==0.26.0','console_scripts','wheel'
__requires__ = 'wheel==0.26.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('wheel==0.26.0', 'console_scripts', 'wheel')()
    )
